"""Activation-code store and validation (SQLite).

Lightweight model for the non-commercial phase:
  - a code is valid while ``active`` is true and not expired
  - optional daily and total usage caps (0 = unlimited)
  - no device binding (can be added later)

The database lives at ``gateway/data/codes.db``.  Codes are generated by
``manage_codes.py``; this module only validates and meters them.
"""

import os
import secrets
import sqlite3
import threading
from datetime import datetime, timedelta

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "codes.db")

# Unambiguous alphabet (no I/L/O/0/1) so codes are easy to type.
_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
_lock = threading.Lock()


class AuthError(Exception):
    """Raised when an activation code is rejected, with an HTTP status."""

    def __init__(self, status_code: int, message: str):
        super().__init__(message)
        self.status_code = status_code
        self.message = message


def _conn() -> sqlite3.Connection:
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS codes(
            code TEXT PRIMARY KEY,
            created_at TEXT NOT NULL,
            expires_at TEXT,
            daily_limit INTEGER NOT NULL DEFAULT 0,
            total_limit INTEGER NOT NULL DEFAULT 0,
            used_daily INTEGER NOT NULL DEFAULT 0,
            used_total INTEGER NOT NULL DEFAULT 0,
            last_daily_reset TEXT NOT NULL DEFAULT '',
            active INTEGER NOT NULL DEFAULT 1
        )
        """
    )
    c.commit()
    return c


def _gen_code() -> str:
    parts = ["".join(secrets.choice(_ALPHABET) for _ in range(4)) for _ in range(4)]
    return "AIES-" + "-".join(parts)


def create_codes(count: int, expires_at: str = None, daily_limit: int = 0, total_limit: int = 0) -> list[str]:
    """Generate ``count`` fresh activation codes and return them.

    ``expires_at`` is an ISO datetime string (or None for no expiry).
    """
    codes = []
    with _lock:
        c = _conn()
        now = datetime.now().isoformat()
        for _ in range(count):
            code = _gen_code()
            c.execute(
                "INSERT INTO codes(code, created_at, expires_at, daily_limit, total_limit) "
                "VALUES(?, ?, ?, ?, ?)",
                (code, now, expires_at, daily_limit, total_limit),
            )
            codes.append(code)
        c.commit()
        c.close()
    return codes


def validate(code: str) -> None:
    """Validate ``code`` and increment its usage counters.

    Raises ``AuthError`` with an appropriate status code (401/429) on failure.
    """
    code = (code or "").strip()
    if not code:
        raise AuthError(401, "缺少激活码")

    with _lock:
        c = _conn()
        try:
            row = c.execute("SELECT * FROM codes WHERE code = ?", (code,)).fetchone()
            if row is None or not row["active"]:
                raise AuthError(401, "激活码无效")

            if row["expires_at"]:
                try:
                    if datetime.now() > datetime.fromisoformat(row["expires_at"]):
                        raise AuthError(401, "激活码已过期")
                except ValueError:
                    pass  # malformed expiry — treat as no expiry

            today = datetime.now().strftime("%Y-%m-%d")
            used_daily = row["used_daily"]
            if row["last_daily_reset"] != today:
                used_daily = 0

            if row["daily_limit"] and used_daily >= row["daily_limit"]:
                raise AuthError(429, "已达今日使用上限，请明日再试")
            if row["total_limit"] and row["used_total"] >= row["total_limit"]:
                raise AuthError(429, "已达总使用上限")

            c.execute(
                "UPDATE codes SET used_daily = ?, used_total = ?, last_daily_reset = ? WHERE code = ?",
                (used_daily + 1, row["used_total"] + 1, today, code),
            )
            c.commit()
        finally:
            c.close()


def revoke(code: str) -> bool:
    """Deactivate a code. Returns False if it does not exist."""
    with _lock:
        c = _conn()
        cur = c.execute("UPDATE codes SET active = 0 WHERE code = ?", (code.strip(),))
        c.commit()
        c.close()
        return cur.rowcount > 0


def list_codes() -> list[dict]:
    """Return every code with its status (admin view)."""
    with _lock:
        c = _conn()
        rows = c.execute("SELECT * FROM codes ORDER BY created_at DESC").fetchall()
        c.close()
        return [dict(r) for r in rows]


def stats() -> dict:
    """Aggregate totals for the admin CLI."""
    with _lock:
        c = _conn()
        total = c.execute("SELECT COUNT(*) AS n FROM codes").fetchone()["n"]
        active = c.execute("SELECT COUNT(*) AS n FROM codes WHERE active = 1").fetchone()["n"]
        used_total = c.execute("SELECT COALESCE(SUM(used_total), 0) AS n FROM codes").fetchone()["n"]
        c.close()
    return {"total": total, "active": active, "total_calls": used_total}
